abitarRevestimentos/urls.py
from django.contrib import admin
from django.urls import include, path
from abitarRevestimentos import views

urlpatterns = [
    path('', views.index, name="index"),
    path('produto/', include('produto.urls')),
    path('categoria/', include('categoria.urls')),
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
]

categoria/urls.py
from django.urls import path

from categoria import views

app_name = 'categoria'
# path('', views.listaProduto, name="listaProduto"),

urlpatterns = [
    path('<slug:slug>/', views.paginaCategoria, name="paginaCategoria"),
]

contas/urls.py
from django.http import request
from django.urls import path

from categoria import views
from django.contrib.auth import views as auth_views
from .forms import CustomAuthenticationForm
app_name = 'contas'
# path('', views.listaProduto, name="listaProduto"),

urlpatterns = [
    path('login2/', auth_views.LoginView.as_view(template_name='registration/login.html', authentication_form=CustomAuthenticationForm(request))),]

produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('', views.listaProduto, name="listaProduto"),
    path('administrar/cadastroPorCodigo/', views.cadastraProdutoPorCodigo, name="cadastraProdutoPorCodigo"),
    path('<slug:codigo>/<slug:slugProduto>/', views.paginaProduto, name="paginaProduto"),
    path('administrar/', views.painelAdmin, name="painelAdminProduto"),
    path('administrar/cadastro', views.cadastraProduto, name='cadastraProduto'),
    path('administrar/buscaBling/<slug:codigo>/', views.buscaProdutoBling, name='buscaProdutoBling'),
    path('administrar/edita/<slug:codigo>/<slug:slugProduto>/', views.editaProduto, name='editaProduto'),
    path('administrar/remove/<slug:codigo>/', views.removeProduto, name='removeProduto'),
    path('administrar/sincrozaPreco/<slug:codigo>/', views.sincronizaPrecoProduto, name='sincronizaPrecoProduto'),
]

produto/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from categoria.models import Categoria
import re

class Produto(models.Model):
    
    codigo = models.CharField(max_length=20, db_index=True, unique=True, primary_key=True)
    nome = models.CharField(max_length=200, db_index = True, unique = False)
    marca = models.CharField(max_length=50, db_index=True, default="")
    imagem = models.CharField(max_length=150, blank = True)
    disponivel = models.BooleanField(default=True, blank = True)
    preco = models.DecimalField(max_digits=5, decimal_places=2, default=3.99)
    altura = models.DecimalField(max_digits=5, decimal_places=2, default=10)
    largura = models.DecimalField(max_digits=5, decimal_places=2, default=10)
    profundidade = models.DecimalField(max_digits=5, decimal_places=2, default=10)
    pesoBruto = models.DecimalField(max_digits=6, decimal_places=2, default=10)
    unidadesPorCaixa = models.DecimalField(max_digits=5, decimal_places=0, default=1, blank=True)
    unidadeDeVenda = models.CharField(max_length=15, default='un', blank = True)
    multiploDeVenda = models.DecimalField(max_digits=5, decimal_places=2, default=1, blank=True)
    descricao = models.TextField(max_length=2000, default="",blank = True)
    slug = models.SlugField(max_length=100, default = '',blank = True)
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, default=None, blank=True)

    def save(self, *args, **kwargs):
        value = self.nome
        if(type(self.multiploDeVenda)==str):
            self.multiploDeVenda = float(self.multiploDeVenda.replace(",", "."))
        self.slug = slugify(value, allow_unicode=False)
        self.descricao = re.sub('<[^>]+>', '', self.descricao)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = ("Produto")
        verbose_name_plural = ("Produtos")
        db_table = 'produto'
        ordering = ('codigo', 'nome',)
        permissions = (("administrativo", "Pode administrar os produtos"),)  

    def __str__(self):
        return f"{self.codigo} -> {self.nome}"

    def getAbsoluteUrl(self):
        return reverse('produto:paginaProduto', args=[self.codigo, self.slug])

    def getPrecoParcelado(self):
        return ("%.2f" %(float(self.preco)/6)).replace(".",",")

produto/views.py
from categoria.models import Categoria
from django.shortcuts import get_object_or_404, redirect, render
import requests
from django.http import HttpResponse
from produto.models import Produto
from produto.forms import PesquisaProdutoForm, PesquisaPorCodigoForm, ProdutoForm, ProdutoCategoriaForm, QuantidadeForm
from decimal import Decimal
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import permission_required


def getFromBling(codigo):
    # busca produto no bling e retorna como json se for encontrado
    payload = {'apikey': 'e5f8af5a3039686600cd5df81b77bbf244abfacc52bb94424df874630b20384f07939108',
               'imagem': 'S'}
    produto = requests.get(
        f'https://bling.com.br/Api/v2/produto/{codigo}/json/', params=payload).json()
    print("antes do try")
    try:
        jsonProduto = produto['retorno']['produtos']
        print(jsonProduto)
        jsonProduto[0]['produto']['preco'] = '%.2f' % float(
            jsonProduto[0]['produto']['preco'])
        jsonProduto[0]['produto']['preco'] = jsonProduto[0]['produto']['preco'].replace(
            ".", ",")
        codigoErro = "Sucesso"

    except KeyError:
        print("produto não encontrado no bling")
        codigoErro = "Falha"
        return None
    try:
        jsonProduto[0]['produto']['camposCustomizados']['m2PorCaixa']
    except:
        jsonProduto[0]['produto']['camposCustomizados'] = {'m2PorCaixa': 1}
    try:
        jsonProduto[0]['produto']['imagem'][0]['link']
    except:
        jsonProduto[0]['produto']['imagem'].append({'link': ""})
    print("fim do get")
    return jsonProduto


@permission_required("administrativo")
def listaProdutoBling(request):
    # lista o codigo de todos os produtos do bling
    url = 'https://bling.com.br/Api/v2/produtos/page=1/json/'
    payload = {'apikey': 'e5f8af5a3039686600cd5df81b77bbf244abfacc52bb94424df874630b20384f07939108',
               'imagem': 'S'}
    page = 1
    produtosJson = {'produtos': []}
    c = 0
    while True:
        urlRequisitada = f'https://bling.com.br/Api/v2/produtos/page={page}/json/'
        produtos = requests.get(
            f'https://bling.com.br/Api/v2/produtos/page={page}/json/', params=payload)
        try:
            jsonAtual = produtos.json()
            for item in jsonAtual['retorno']['produtos']:
                item['numero'] = c
                produtosJson['produtos'].append(item)
                if(c == 0):
                    print(item)
                c += 1
            page += 1
        except KeyError:
            break
    print(c)
    return render(request, 'produto/index.html', {'produtos': produtosJson})


@permission_required("administrativo")
def buscaProdutoBling(request, codigo):
    # view de busca do produto por codigo para cadastro no bling
    print(codigo)
    url = f'https://bling.com.br/Api/v2/produto/{codigo}/json/'
    print(url)
    payload = {'apikey': 'e5f8af5a3039686600cd5df81b77bbf244abfacc52bb94424df874630b20384f07939108',
               'imagem': 'S'}
    produto = requests.get(url, params=payload).json()
    try:
        jsonProduto = produto['retorno']['produtos']
        codigoErro = "Sucesso"
    except:
        jsonProduto = {}
        codigoErro = "Falha"
    print(codigoErro)
    return render(request, 'produto/pagina.html', {'produto': jsonProduto, 'codigoErro': codigoErro})


@permission_required("administrativo")
def cadastraProdutoPorCodigo(request):
    # cadastra o produto já buscado no bling com os dados de lá
    print("cadastro por codigo")
    produtoDicionario = ""
    if request.GET:
        print("é get")
        try:
            del request.session['codigoSelecionado']
        except KeyError:
            pass

        formCodigo = PesquisaPorCodigoForm(request.GET)
        if formCodigo.is_valid():
            codigo = formCodigo.cleaned_data['codigo']
            print(f"{codigo} é valido no form")
            produto = getFromBling(codigo)
            if not produto:
                print("produto não encontrado no bling")
                formCodigo = PesquisaPorCodigoForm()
                messages.add_message(
                    request, messages.ERROR, 'Produto não encontrado!')
                return render(request, 'produto/cadastroPorCodigo.html', {'form': formCodigo, 'produto': ""})

            produtoDicionario = {"codigo": produto[0]['produto']['codigo'],
                                 "nome": produto[0]['produto']['descricao'],
                                 "marca": produto[0]['produto']['marca'],
                                 "imagem": produto[0]['produto']['imagem'][0]['link'],
                                 "disponivel": True,
                                 "preco": produto[0]['produto']['preco'],
                                 "altura": produto[0]['produto']['alturaProduto'],
                                 "largura": produto[0]['produto']['larguraProduto'],
                                 "profundidade": produto[0]['produto']['profundidadeProduto'],
                                 "pesoBruto": produto[0]['produto']['pesoBruto'],
                                 "unidadesPorCaixa": produto[0]['produto']['itensPorCaixa'],
                                 "multiploDeVenda": produto[0]['produto']['camposCustomizados']['m2PorCaixa'],
                                 "unidadeDeVenda": produto[0]['produto']['unidade'],
                                 "descricao": produto[0]['produto']['descricaoCurta'],
                                 }

            request.session['codigoSelecionado'] = produtoDicionario['codigo']
            print("request é:")
            print(
                f"{request.session['codigoSelecionado']} custa {produtoDicionario['preco']}")
    elif request.POST:
        print("é um post")
        formCategoria = ProdutoCategoriaForm(request.POST)
        categoria = None
        if formCategoria.is_valid():
            print(type(formCategoria.cleaned_data['categoria']))
            categoria = formCategoria.cleaned_data['categoria']
        try:
            produto = get_object_or_404(
                Produto, codigo=request.session['codigoSelecionado'])
            messages.add_message(
                request, messages.ERROR, f'O produto {produto.codigo} já está cadastrado no sistema!')
        except:
            produto = getFromBling(request.session['codigoSelecionado'])
            del request.session['codigoSelecionado']
            if not produto:
                formCodigo = PesquisaPorCodigoForm()
                return render(request, 'produto/cadastroPorCodigo.html', {'form': formCodigo, 'produto': ""})

            produtoBling = Produto(codigo=produto[0]['produto']['codigo'],
                                   nome=produto[0]['produto']['descricao'],
                                   marca=produto[0]['produto']['marca'],
                                   imagem=produto[0]['produto']['imagem'][0]['link'],
                                   disponivel=True,
                                   preco=float(
                                       produto[0]['produto']['preco'].replace(",", ".")),
                                   altura=float(
                                       produto[0]['produto']['alturaProduto']),
                                   largura=float(
                                       produto[0]['produto']['larguraProduto']),
                                   profundidade=float(
                                       produto[0]['produto']['profundidadeProduto']),
                                   pesoBruto=float(
                                       produto[0]['produto']['pesoBruto']),
                                   unidadesPorCaixa=float(
                                       produto[0]['produto']['itensPorCaixa']),
                                   unidadeDeVenda=produto[0]['produto']['unidade'],
                                   # colocar vinculado a categoria
                                   multiploDeVenda=produto[0]['produto']['camposCustomizados']['m2PorCaixa'],
                                   descricao=produto[0]['produto']['descricaoCurta'],
                                   categoria=categoria,
                                   )
            produtoBling.save()
            messages.add_message(
                request, messages.SUCCESS, f'O produto {produtoBling.codigo} foi cadastrado no com sucesso sistema!')
        formCodigo = PesquisaPorCodigoForm()
    else:
        print("request inicial")
        try:
            del request.session['codigoSelecionado']
        except KeyError:
            pass
        formCodigo = PesquisaPorCodigoForm()
    formCategoria = ProdutoCategoriaForm()
    print(produtoDicionario)
    return render(request, 'produto/cadastroPorCodigo.html', {'form': formCodigo, 'formCategoria': formCategoria,  'produto': produtoDicionario})

def paginaProduto(request, codigo, slugProduto):
    produto = get_object_or_404(Produto, codigo=codigo)
    produto.descricao = produto.descricao.splitlines()
    formQuantidade = QuantidadeForm(multiploDeVenda=produto.multiploDeVenda)
    categoriasProduto = []
    categoria = produto.categoria
    while(categoria):
        print(f"{categoria} tem id {categoria.id}")
        categoriasProduto.insert(0, categoria)
        categoria = categoria.categoriaPai
    print(categoriasProduto)
    if request.POST:
        mensagem = f"Olá, tenho interesse em: {request.POST.get('quantidade')} {produto.unidadeDeVenda} do produto: {produto.nome}"
        print(mensagem)
        return redirect(f"https://api.whatsapp.com/send?phone=5521995441122&text={mensagem}")

    return render(request, 'produto/paginaProduto.html', {'produto': produto, 'formQuantidade': formQuantidade, 'categoriasProduto': categoriasProduto})


def listaProduto(request):
    form = PesquisaProdutoForm(request.GET)
    if form.is_valid():
        nome = form.cleaned_data['nome']

produto/templates/produto/cadastroPorCodigo.html
{% extends 'base.html' %}
{% load static %}
{% block corpo %}
<div class="my-4 container">
    <div class="d-flex">
        <h2 class="my-3">Cadastro por código</h2>
        <div class="ml-auto d-flex flex-column">
            <a href="{% url 'produto:painelAdminProduto'%}" class="text-dark text-decoration-none h6 my-auto"><i class="fas fa-arrow-left mr-2"></i>Voltar</a>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class=" alert font-weight-bold {{message.tags}} alert-dismissible my-2 w-75 mx-auto"{% endif %} role="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    <form method="GET" action="{% url 'produto:cadastraProdutoPorCodigo' %}" class="form-inline mb-sm-2 my-lg-auto mx-auto">
        <div class="input-group">
            {{form.codigo}}
            <div class="input-group-append">
                <button id="botao" type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i> Buscar
                </button>
            </div>
        </div>
    </form>
    {% if produto != "" %}
        <div class="card w-75 mx-auto my-4 px-3 py-2">
            <h5 class="font-weight-bold mb-3">{{produto.nome}}</h5>
            <div class="row">
                <div class="col-lg-6 d-flex align-items-center mb-2 mb-lg-0">   
                    <img class="img-fluid w-100" src="{{produto.imagem}}"
                    alt="{{produto.nome}}">
                </div>
                <div class="col-lg-6 py-2 d-flex flex-column">
                        <div>
                            <h5 class="d-inline font-weight-bolder">Código: <h6 class="d-inline my-auto font-weight-normal">{{produto.codigo}}</h6></h5>
                        </div>
                        <div>
                            <h5 class="d-inline font-weight-bolder">Altura: <h6 class="d-inline my-auto font-weight-normal">{{produto.altura}} cm</h6></h5>
                        </div>
                        <div>
                            <h5 class="d-inline font-weight-bolder">Largura: <h6 class="d-inline my-auto font-weight-normal">{{produto.largura}} cm</h6></h5>
                        </div>
                        <div>
                            <h5 class="d-inline font-weight-bolder">Profundidade: <h6 class="d-inline my-auto font-weight-normal">{{produto.profundidade}} cm</h6></h5>
                        </div>
                        <div>
                            <h5 class="d-inline font-weight-bold">Unidades por Caixa: <h6 class="d-inline my-auto font-weight-normal">{{produto.unidadesPorCaixa}}</h6></h5>
                        </div>
                        {% if produto.unidadeDeVenda == 'm²' %}
                        <div>
                            <h5 class="d-inline font-weight-bolder font-weight-bolder">M² por Caixa: <section class="d-inline my-auto font-weight-normal">{{produto.multiploDeVenda}} m²</section></h5>
                        </div>
                        {% endif %}
                        <h4 class="my-4 text-center mx-auto">R$ {{produto.preco}}/{{produto.unidadeDeVenda}}</h4>
                        
                        <form method="POST" action="{% url 'produto:cadastraProdutoPorCodigo' %}" class="mt-auto formSelect">
                            {{formCategoria.categoria}} 
                            <div class="mt-2 mx-auto">
                                <button id="botao" type="submit" class="ml-auto btn btn-primary">
                                    {% csrf_token %}
                                    <i class="fas fa-paper-plane"></i> Enviar
                                </button>
                            </div>
                        </form>
                        
                </div>
            </div>
        </div>
        
    {% endif %}
</div>
{% endblock %}

produto/templates/produto/cadastroProduto.html
{% extends 'base.html' %}
{% load static %}
{% block corpo %}
	<div class="mx-auto container py-4">
		<h2 class="carterOne">
		{% if 'produto_id' in request.session %}
			Alterar Produto
		{% else %}
			Cadastrar Produto
		{% endif %}
		</h2>
		{% if messages %}
			{% for message in messages %}
			<div {% if message.tags %} class=" alert font-weight-bold {{message.tags}} alert-dismissible my-2 w-75 mx-auto"{% endif %} role="alert">
				<button type="button" class="close" data-dismiss="alert">×</button>
				{{ message }}
			</div>
			{% endfor %}
    	{% endif %}
		<form action="{% url 'produto:cadastraProduto' %}" method="POST" class="pb-4 carter" novalidate style="min-height: 323px">
			{{form.as_p}}

			<div class="d-flex justify-content-end">
				
				<button id="botao" type="submit" class="btn btn-primary">
				{% csrf_token %}
					{% if 'produtoEditado' in request.session %}
					<i class="fas fa-edit mr-1"></i> Alterar
					{% else %}
					<i class="fas fa-plus-circle mr-1"></i> Cadastrar
					{% endif %}
				</button>
			</div>
		</form>
		
	</div>
{% endblock %}

produto/templates/produto/index.html
{% extends 'base.html' %}
{% load static %}
{% block corpo %}
{% for row in produtos.produtos %}
    <p>{{row.numero}} -> {{row.produto.codigo}}</p>
{% endfor %}
{% endblock %}

produto/templates/produto/pagina.html
{% extends 'base.html' %}
{% load static %}
{% block corpo %}
    {% if produto %}
        <button type="button" class="btn btn-primary">Primary</button>
        {{produto}}
    {% else %}
        Produto não encontrado
    {% endif %}
{% endblock %}

produto/templates/produto/paginaProduto.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
{{produto.nome}}
{% endblock %}

{% block corpo %}


<div class="mx-auto container pt-2">

	{% if messages %}
		{% for message in messages %}
		<div {% if message.tags %} class=" alert font-weight-bold {{message.tags}} alert-dismissible my-2 w-75 mx-auto"{% endif %} role="alert">
			<button type="button" class="close" data-dismiss="alert">×</button>
			{{ message }}
		</div>
		{% endfor %}
	{% endif %}

	<nav aria-label="breadcrumb">
		<ol class="breadcrumb mt-2 mb-3">
			<li class="breadcrumb-item"><a href="/">Página Inicial</a></li>
			<li class="breadcrumb-item"><a href="{% url 'produto:listaProduto' %}">Todos os Produtos</a></li>
			{% for categoria in categoriasProduto %}
				<li class="breadcrumb-item" aria-current="page"><a href="{% url 'categoria:paginaCategoria' categoria.slug %}">{{categoria}}</a></li>
			{% endfor %}

		</ol>
	</nav>
	<div class="card h-100 mb-3 px-5 py-4">
		<div class="row">
			<div class="col-lg-5 d-flex align-items-center mb-3 mb-lg-0">
				<div>
					<img class="img-fluid w-100 mb-2" src="{{ produto.imagem }}" alt="{{produto.nome}}">
					<div class="d-flex justify-content-around">
						<a href="#" type="button" class="text-pink"><i class="fas fa-heart"></i>
							Lista de Desejos</a>
						<a href="#" type="button" class="text-black-50"><i class="fas fa-share-alt"></i>
							Compartilhar</a>
					</div>
				</div>
			</div>
			<div class="col-lg-7">
				<div class="card border-0">
					<h4 class="mb-0">{{produto.nome}}
					</h4>
					<div class="mb-2">Marca: {{produto.marca}}</div>
					<div class="d-flex align-items-center mb-2">
						<span class="text-black-50">Código: {{produto.codigo}}</span>
					</div>
					<hr class="mt-0 mb-3">

					<div class="row mb-4">
						<div class="col-sm-7 col-md-6 mb-3 mb-sm-0 d-flex flex-column justify-content-center">
							<h5 class="mb-3">de <strike class="ml-1 ">{{ produto.preco }}</strike></h5>
							<div class="d-flex align-items-center mb-2">
								<h4 class="mb-0">por</h4>
								<h4 class="precoCarrinho ml-1 mb-0">R$ {{ produto.preco }}</h4>
								{% if produto.unidadeDeVenda == 'm²' %}
								<h6 class="mb-0">/m²</h6>
								{% endif %}
							</div>
							<h5 class="mb-0">ou em até 6x de {{ produto.getPrecoParcelado }}</h5>
						</div>

						<form method="POST" action="{{produto.getAbsoluteUrl}}"
							class="col-sm-5 col-md-6 d-flex flex-column align-items-center justify-content-center">
							<div>
								<button class="btn btn-primary adicionarCarrinho my-2" type="submit">
									<h4 class="my-1">Comprar</h4>
								</button>
								{% csrf_token %}
							</div>
							<div class="d-flex flex-column mx-2 mb-2 mt-0 inputQuantidade">
								<div class="input-group mb-1">
									<div class="input-group-prepend">
										<button type="button" id="" class="diminuiQuantidade btn btn-outline-primary"
											data-type="minus" data-field="quantidade"><i
												class="fas fa-minus font-22 mb-0 align-middle"></i></button>
									</div>
									<input type="text" id="quantidade" name="quantidade"
										data-step="{{produto.multiploDeVenda}}" class="form-control text-center"
										value="{{produto.multiploDeVenda}}" min="{{produto.multiploDeVenda}}" max="999">
									<div class="input-group-append">
										<button type="button" id="" class="aumentaQuantidade btn btn-outline-success"
											data-type="plus" data-field="quantidade"><i
												class="fas fa-plus font-22 mb-0 align-middle"></i></button>
									</div>
								</div>
								{% if produto.unidadeDeVenda == 'm²' %}
									<h6 class="text-center font-14 mb-0">Cobertura em M²</h6>
								{% else %}
									<h6 class="text-center font-14 mb-0">Unidades</h6>
								{% endif %}
							</div>

						</form>
					</div>
					<div class="d-flex align-items-center flex-column">
						<h6 class="">Calcular frete e prazo de entrega:</h6>
						<div class="input-group inputCepFrete">
							<input id="inputCepFrete" class="form-control mr-0 inputFrete" type="text"
								placeholder="Insira o CEP" aria-label="Calcule o Frete">
							<div class="input-group-append">
								<button class="btn btn-warning fontWhite" type="button">OK</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="card px-4 py-4 mb-3">
		<h3 class="carterOne mb-3 font-weight-bolder">Descrição do Produto</h3>
		{% for paragrafo in produto.descricao %}
		<p class="mb-1">{{paragrafo}}</p>
		{% endfor %}

	</div>
</div>


{% endblock %}

produto/templates/produto/painelAdmin.html
{% extends 'base.html' %}
{% load static %}
{% block corpo %}
<div class="container">
    <div class="d-flex">
        <h2 class="my-3">Produtos Cadastrados</h2>
        <div class="ml-auto d-flex flex-column">
            <a href="{% url 'produto:cadastraProdutoPorCodigo'%}" class="text-dark text-decoration-none h6 my-auto"><i
                    class="fas fa-plus mr-2 text-success"></i>Novo Produto</a>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class=" alert font-weight-bold {{message.tags}} alert-dismissible my-2 w-75 mx-auto"{% endif %} role="alert">
            <button type="button" class="close" data-dismiss="alert">×</button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if produtos %}
    <div class="row">
        {% for produto in produtos %}
        <div class="col-lg-6">
            <div class="card p-2 mb-3">
                <div class="row cardProdutoAdmin">
                    <div class="my-auto mx-auto col-lg-4 col-md-5 col-sm-6 justify-content-center align-items-center d-flex"
                        style="height: 150px">
                        <img class="img-fluid h-100" src="{{ produto.imagem }}" alt="{{ produto.nome }}">
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-6 mt-1 d-flex flex-column justify-content-start">
                        <div class="d-flex justify-content-start align-items-center maxLines">
                            <h5 class="card-title">{{produto.nome}}</h5>
                        </div>
                        <h5 class="text-primary font-weight-bold mb-2 precoCarrinho">
                            R$ {{produto.preco}}
                        </h5>
                        <div class="mt-auto d-flex justify-content-between">
                            <button onclick="location.href='{{produto.getAbsoluteUrl}}'"
                                class="btn btn-outline-dark">Visualizar</button>
                            <div class="dropdown align-self-end">
                                <a class="h6 mr-3 mb-3" data-toggle="dropdown" href="#"><i
                                        class="fas fa-ellipsis-h"></i></a>
                                <div class="dropdown-menu">
                                    <a href="{% url 'produto:editaProduto' produto.codigo produto.slug %}" class="text-dark text-decoration-none dropdown-item font-14"><i
                                            class="h6 fas fa-edit mr-2"></i>Editar</a>
                                    <form action="{% url 'produto:removeProduto' produto.codigo %}" method="POST"
                                        id="formRemoverProduto">
                                        {% csrf_token %}
                                    </form>
                                    <a href="#" onClick="document.getElementById('formRemoverProduto').submit();"
                                        class="text-dark text-decoration-none dropdown-item font-14">
                                        <i class="h6 text-primary fas fa-trash-alt mr-2"></i>Excluir
                                    </a>
                                    <a href="{% url 'produto:sincronizaPrecoProduto' produto.codigo %}"
                                        class="text-dark text-decoration-none dropdown-item font-14"><i
                                            class="h6 text-success fas fa-sync-alt mr-2"></i>Sincronizar Preço</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
    {% if produtos.has_other_pages %}
    <nav aria-label="Navegação de página exemplo">
        <ul class="pagination justify-content-center">
            {% if produtos.has_previous %}
            <li class='page-item'><a class='page-link'
                    href='?pagina={{ produtos.previous_page_number }}&nome={{nomePesquisado}}'>Anterior</a>
            </li>
            {% else %}
            <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Anterior</a></li>
            {% endif %}
            {% for i in produtos.paginator.page_range %}
            {% if produtos.number == i %}
            <li class='page-item active'><a class='page-link' href='#'>{{ i }} </a></li>
            {% else %}
            <li class='page-item'><a class='page-link' href='?pagina={{ i }}&nome={{nomePesquisado}}'>{{ i }}</a></li>
            {% endif %}
            {% endfor %}
            {% if produtos.has_next %}
            <li class='page-item'><a class='page-link'
                    href='?pagina={{ produtos.next_page_number }}&nome={{nomePesquisado}}'>Próxima</a></li>
            {% else %}
            <li class='page-item disabled'><a class='page-link' href='#' tabindex='-1'>Próxima</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    {% else %}
    <div class="d-flex justify-content-center align-items-center carterOne">
        Nenhum resultado foi encontrado...
    </div>
    {% endif %}
</div>

{% endblock %}